# Generated by Django 4.2.8 on 2024-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuser_has_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_workout_time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_workout_times',
            field=models.CharField(blank=True, choices=[('2', '2 times a week'), ('3', '3 times a week'), ('4', '4 times a week')], max_length=1, null=True),
        ),
    ]
