# Generated by Django 4.2.8 on 2024-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_customuser_preferred_workout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_equipment',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Gym equipment', 'Gym equipment'), ('Resistance bands', 'Resistance bands')], max_length=20, null=True),
        ),
    ]
