# Generated by Django 4.2.8 on 2024-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_customuser_available_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='available_equipment',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Resistance bands', 'Resistance bands'), ('Gym equipment', 'Gym equipment')], max_length=20, null=True),
        ),
    ]
