# Generated by Django 4.2.8 on 2024-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_customuser_available_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('age', models.CharField(max_length=50)),
                ('injury', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Flexibility', 'Flexibility'), ('Strength', 'Strength')], max_length=20)),
                ('equipment', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
