# Generated by Django 4.2.8 on 2024-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='bmi',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
