# Generated by Django 4.2.8 on 2024-08-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_exercise_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='available_equipment',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Resistance Band', 'Resistance Band'), ('Gym', 'Gym')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='injuries',
            field=models.CharField(blank=True, choices=[('Achilles', 'Achilles'), ('ACL', 'ACL'), ('Meniscus', 'Meniscus')], max_length=20, null=True),
        ),
    ]
