# Generated by Django 4.2.8 on 2024-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_customuser_available_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='goals',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='injuries',
            field=models.CharField(blank=True, choices=[('Torn Achilles', 'Torn Achilles'), ('Torn ACL', 'Torn ACL'), ('Torn Meniscus', 'Torn Meniscus')], max_length=20, null=True),
        ),
    ]
