# Generated by Django 4.2.8 on 2024-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='week1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='week2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='week3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
