# Generated by Django 4.2.8 on 2024-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_exercise_week1_exercise_week2_exercise_week3'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
