# Generated by Django 4.2.8 on 2024-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_customuser_plan_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_workout_times',
            field=models.CharField(blank=True, choices=[('3', '3 times a week'), ('4', '4 times a week'), ('5', '5 times a week')], max_length=1, null=True),
        ),
    ]
