# Generated by Django 4.2.8 on 2024-09-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_alter_customuser_preferred_workout_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
